# Generated by Django 5.2 on 2025-05-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fullname', models.CharField(max_length=50)),
                ('s_age', models.IntegerField()),
                ('s_grade', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'students',
            },
        ),
    ]
