# Generated by Django 5.2 on 2025-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_fname', models.CharField(max_length=25)),
                ('t_lname', models.CharField(max_length=25)),
                ('t_age', models.IntegerField()),
                ('t_xp_year', models.IntegerField()),
                ('t_email', models.EmailField(max_length=254)),
                ('t_subject', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'teachers',
            },
        ),
    ]
